{
 "title": "Photovoltaik",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "tz", "label": "Timezone", "query": "${VAR_TZ}" }
  ]
 },
 "panels": [
  { "title": "Live Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energy Usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Home Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT \"mean_load_instant_power\" FROM \"http\" WHERE $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_Load" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "Solar Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "To Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT max(from_grid) - max(to_grid) FROM autogen.http WHERE $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "P_Grid" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "P_Grid::field", "operator": "<", "value": "0" }
     ],
     "tz": "$tz"
    },
    {
     "alias": "From Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT max(from_grid) - max(to_grid) FROM autogen.http WHERE $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "P_Grid" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "P_Grid::field", "operator": ">", "value": "0" }
     ],
     "tz": "$tz"
    },
    {
     "alias": "Autonomy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "select": [
      [
       { "params": [ "rel_Autonomy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    { "target": [ "sun_altitude" ] },
    {
     "alias": "Grid Down",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT mean(\"ErrorCode\") FROM \"autogen\".\"inverter\" WHERE (\"ErrorCode\"::field = 1063 or \"ErrorCode\"::field = 1120) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ErrorCode" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ErrorCode::field", "operator": "=", "value": "1067" }
     ]
    },
    {
     "alias": "Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storage",
     "select": [
      [
       { "params": [ "StateOfCharge_Relative" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "To Storage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "select": [
      [
       { "params": [ "P_Akku" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "P_Akku::field", "operator": "<", "value": "0" }
     ],
     "tz": "$tz"
    },
    {
     "alias": "From Storage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "select": [
      [
       { "params": [ "P_Akku" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "P_Akku::field", "operator": ">", "value": "0" }
     ],
     "tz": "$tz"
    }
   ]
  },
  { "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 } },
  {
   "title": "Autonomy",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Self consumption",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  { "gridPos": { "h": 6, "w": 16, "x": 0, "y": 18 } },
  {
   "title": "Expected yield",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Today",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pv_forecast_watt_hours_day",
     "query": "SELECT first(\"value\") FROM \"autogen\".\"pv_forecast_watt_hours_day\" WHERE $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "Tomorrow",
     "query": "SELECT last(\"value\") FROM \"autogen\".\"pv_forecast_watt_hours_day\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  { "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 } },
  { "title": "Energy Meters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Home Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "powerflow",
     "query": "SELECT (last(\"E_Total\") - first(\"E_Total\")) as produced FROM \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n",
     "select": [
      [
       { "params": [ "P_Load" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600 * -1" ], "type": "math" }
      ]
     ]
    },
    {
     "measurement": "powerflow",
     "query": "SELECT -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid, (last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\")) as from_grid FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')\n",
     "select": [
      [
       { "params": [ "P_Load" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600 * -1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Local Energy Consumption",
   "type": "stat",
   "description": "comprises power sourced both from the battery and utilized directly excluding energy from/to grid",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "measurement": "powerflow",
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n",
     "select": [
      [
       { "params": [ "E_Total" ], "type": "field" }
      ]
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Local Energy Production",
   "type": "stat",
   "description": "comprises power sourced both from the battery and utilized directly",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "measurement": "powerflow",
     "query": "SELECT last(\"E_Total\") - first(\"E_Total\") FROM \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "E_Total" ], "type": "field" }
      ]
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "From Storage",
   "type": "stat",
   "description": "This is an approximation as it requires calculation using an integral function, since no value in the API accurately reflects the actual value.",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "powerflow",
     "query": "SELECT integral(\"P_Akku\", 1h) FROM \"autogen\".\"powerflow\" WHERE (\"P_Akku\"::field >= 0) AND $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_Akku" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "P_Akku::field", "operator": ">", "value": "0" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "To Storage",
   "type": "stat",
   "description": "This is an approximation as it requires calculation using an integral function, since no value in the API accurately reflects the actual value.",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "powerflow",
     "query": "SELECT abs(integral(\"P_Akku\", 1h)) FROM \"autogen\".\"powerflow\" WHERE (\"P_Akku\"::field <= 0) AND $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_Akku" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "P_Akku::field", "operator": "<", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "From Grid",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "measurement": "powerflow",
     "query": "SELECT max(\"EnergyReal_WAC_Plus_Absolute\") -  min(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_Grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "P_Grid::field", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "To Grid",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "powerflow",
     "query": "SELECT max(\"EnergyReal_WAC_Minus_Absolute\") -  min(\"EnergyReal_WAC_Minus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_Grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600 * -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "P_Grid::field", "operator": "<", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Net Grid Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "powerflow",
     "query": "SELECT (last(\"EnergyReal_WAC_Plus_Absolute\") - first(\"EnergyReal_WAC_Plus_Absolute\")) - (last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')\n",
     "select": [
      [
       { "params": [ "P_Grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Autonomy",
   "type": "stat",
   "description": "comprises power sourced both from the battery and utilized directly",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT (last(\"E_Total\") - first(\"E_Total\")) as produced FROM \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_Load" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " /1000/ 3600" ], "type": "math" }
      ]
     ],
     "tz": "$tz"
    },
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid, (last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\")) as from_grid FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_Load" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " /1000/ 3600" ], "type": "math" }
      ]
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Total solar energy production",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "powerflow",
     "query": "SELECT last(\"E_Total\") FROM \"autogen\".\"powerflow\"",
     "select": [
      [
       { "params": [ "E_Total" ], "type": "field" }
      ]
     ],
     "tz": "$tz"
    }
   ]
  },
  { "title": "Estimated savings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Savings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT (last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid, (last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\")) as from_grid FROM \"autogen\".\"smartmeter\" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')\n"
    },
    {
     "query": "SELECT (last(\"E_Total\") - first(\"E_Total\")) as produced FROM \"autogen\".\"powerflow\" WHERE $timeFilter GROUP BY time(1d) fill(0)  tz('${tz:raw}')"
    },
    {
     "query": "SELECT mean(\"sell\")/100000 as sellEuroWh, mean(\"buy\")/100000 as buyEuroWh FROM \"autogen\".\"electricity\" GROUP BY time(1d) fill(previous) tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Savings this month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT (last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid, (last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\")) as from_grid FROM \"autogen\".\"smartmeter\" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')\n"
    },
    {
     "query": "SELECT (last(\"E_Total\") - first(\"E_Total\")) as produced FROM \"autogen\".\"powerflow\" WHERE $timeFilter GROUP BY time(1d) fill(0)  tz('${tz:raw}')"
    },
    {
     "query": "SELECT mean(\"sell\")/100000 as sellEuroWh, mean(\"buy\")/100000 as buyEuroWh FROM \"autogen\".\"electricity\" GROUP BY time(1d) fill(previous) tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Savings last month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT (last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid, (last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\")) as from_grid FROM \"autogen\".\"smartmeter\" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')\n"
    },
    {
     "query": "SELECT (last(\"E_Total\") - first(\"E_Total\")) as produced FROM \"autogen\".\"powerflow\" WHERE $timeFilter GROUP BY time(1d) fill(0)  tz('${tz:raw}')"
    },
    {
     "query": "SELECT mean(\"sell\")/100000 as sellEuroWh, mean(\"buy\")/100000 as buyEuroWh FROM \"autogen\".\"electricity\" GROUP BY time(1d) fill(previous) tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Savings this year",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT (last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid, (last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\")) as from_grid FROM \"autogen\".\"smartmeter\" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')\n"
    },
    {
     "query": "SELECT (last(\"E_Total\") - first(\"E_Total\")) as produced FROM \"autogen\".\"powerflow\" WHERE $timeFilter GROUP BY time(1d) fill(0)  tz('${tz:raw}')"
    },
    {
     "query": "SELECT mean(\"sell\")/100000 as sellEuroWh, mean(\"buy\")/100000 as buyEuroWh FROM \"autogen\".\"electricity\" GROUP BY time(1d) fill(previous) tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Savings last year",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT (last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid, (last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\")) as from_grid FROM \"autogen\".\"smartmeter\" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')\n"
    },
    {
     "query": "SELECT (last(\"E_Total\") - first(\"E_Total\")) as produced FROM \"autogen\".\"powerflow\" WHERE $timeFilter GROUP BY time(1d) fill(0)  tz('${tz:raw}')"
    },
    {
     "query": "SELECT mean(\"sell\")/100000 as sellEuroWh, mean(\"buy\")/100000 as buyEuroWh FROM \"autogen\".\"electricity\" GROUP BY time(1d) fill(previous) tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Total savings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT (last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid, (last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\")) as from_grid FROM \"autogen\".\"smartmeter\" GROUP BY time(1d) fill(0) tz('${tz:raw}')\n"
    },
    {
     "query": "SELECT (last(\"E_Total\") - first(\"E_Total\")) as produced FROM \"autogen\".\"powerflow\" GROUP BY time(1d) fill(0)  tz('${tz:raw}')"
    },
    {
     "query": "SELECT mean(\"sell\")/100000 as sellEuroWh, mean(\"buy\")/100000 as buyEuroWh FROM \"autogen\".\"electricity\" GROUP BY time(1d) fill(previous) tz('${tz:raw}')"
    }
   ]
  },
  { "title": "Autonomy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Autonomy yesterday",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Autonomy this month",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Autonomy last month",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Autonomy this year",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Autonomy last year",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Self consumption yesterday",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Self consumption this month",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Self consumption last month",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Self consumption this year",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Self consumption last year",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "SELECT  (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter tz('${tz:raw}')\n"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter tz('${tz:raw}')"
    }
   ]
  },
  { "title": "Detailed Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Local Energy Production",
   "type": "timeseries",
   "description": "comprises power sourced both from the battery and utilized directly excluding energy feed into grid",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Local Energy Production",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT last(E_Total) - first(E_Total) FROM \"autogen\".\"powerflow\" WHERE $timeFilter GROUP BY time(1d) fill(null) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000/3600" ], "type": "math" }
      ]
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Home Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT (last(\"E_Total\") - first(\"E_Total\")) as produced, -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) as to_grid, (last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\")) as from_grid FROM \"autogen\".\"smartmeter\",  \"autogen\".\"powerflow\" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_Load" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " /1000/ 3600" ], "type": "math" }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "From Grid",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "From Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "From Storage",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT integral(\"P_Akku\", 1h) FROM \"autogen\".\"powerflow\" WHERE (\"P_Akku\"::field >= 0) AND $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "from_pw" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "To Storage",
     "query": "SELECT integral(\"P_Akku\", 1h) FROM \"autogen\".\"powerflow\" WHERE (\"P_Akku\"::field <= 0) AND $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')"
    }
   ]
  },
  {
   "title": "Grid Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "From Grid",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT last(\"EnergyReal_WAC_Plus_Absolute\") -  first(\"EnergyReal_WAC_Plus_Absolute\") FROM \"autogen\".\"smartmeter\" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_Grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "P_Grid::field", "operator": ">", "value": "0" }
     ],
     "tz": "$tz"
    },
    {
     "alias": "To Grid",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT -(last(\"EnergyReal_WAC_Minus_Absolute\") -  first(\"EnergyReal_WAC_Minus_Absolute\")) FROM \"autogen\".\"smartmeter\" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_Grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "P_Grid::field", "operator": "<", "value": "0" }
     ],
     "tz": "$tz"
    }
   ]
  },
  { "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Daily production grouped by kW",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": ">10kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field >= 10000) AND $timeFilter GROUP BY time(1d) fill(null) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "9-10 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 10000) AND  (\"P_PV\"::field >= 9000)  AND $timeFilter GROUP BY time(1d) fill(null) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "8-9 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 9000) AND  (\"P_PV\"::field >= 8000)  AND $timeFilter GROUP BY time(1d) fill(null) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "7-8 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 8000) AND  (\"P_PV\"::field >= 7000)  AND $timeFilter GROUP BY time(1d) fill(null) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "6-7 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 7000) AND  (\"P_PV\"::field >= 6000)  AND $timeFilter GROUP BY time(1d) fill(null) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "5-6 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 6000) AND  (\"P_PV\"::field >= 5000)  AND $timeFilter GROUP BY time(1d) fill(null) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "4-5 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 5000) AND  (\"P_PV\"::field >=4000)  AND $timeFilter GROUP BY time(1d) fill(null) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "3-4 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 4000) AND  (\"P_PV\"::field >= 3000)  AND $timeFilter GROUP BY time(1d) fill(null) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "2-3 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 3000) AND  (\"P_PV\"::field >= 2000)  AND $timeFilter GROUP BY time(1d) fill(null) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "1-2 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 2000) AND  (\"P_PV\"::field >= 1000)  AND $timeFilter GROUP BY time(1d) fill(null) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "<1kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 1000) AND  (\"P_PV\"::field >= 1)  AND $timeFilter GROUP BY time(1d) fill(null) tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    }
   ]
  },
  {
   "title": "Monthly production grouped by kW",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": ">10kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field >= 10000) AND $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "9-10 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 10000) AND  (\"P_PV\"::field >= 9000)  AND $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "8-9 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 9000) AND  (\"P_PV\"::field >= 8000)  AND $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "7-8 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 8000) AND  (\"P_PV\"::field >= 7000)  AND $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "6-7 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 7000) AND  (\"P_PV\"::field >= 6000)  AND $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "5-6 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 6000) AND  (\"P_PV\"::field >= 5000)  AND $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "4-5 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 5000) AND  (\"P_PV\"::field >=4000)  AND $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "3-4 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 4000) AND  (\"P_PV\"::field >= 3000)  AND $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "2-3 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 3000) AND  (\"P_PV\"::field >= 2000)  AND $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "1-2 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 2000) AND  (\"P_PV\"::field >= 1000)  AND $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    },
    {
     "alias": "<1 kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "powerflow",
     "query": "SELECT count(\"P_PV\") FROM \"autogen\".\"powerflow\" WHERE (\"P_PV\"::field < 1000) AND  (\"P_PV\"::field >= 1)  AND $timeFilter tz('${tz:raw}')",
     "select": [
      [
       { "params": [ "P_PV" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "P_PV::field", "operator": ">", "value": "9000" }
     ]
    }
   ]
  },
  { "title": "Smart meter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "String Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "Voltage_AC_Phase_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "Voltage_AC_Phase_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "Voltage_AC_Phase_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "String Current",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "P1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "Current_AC_Phase_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "P2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "Current_AC_Phase_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "P3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "Current_AC_Phase_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "String Power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Apparent S P1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "PowerApparent_S_Phase_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "Apparent S P2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "PowerApparent_S_Phase_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "Apparent S P3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "PowerApparent_S_Phase_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "Reactive Q P1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "PowerReactive_Q_Phase_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "Reactive Q P2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "PowerReactive_Q_Phase_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "Reactive Q P3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "PowerReactive_Q_Phase_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "Real P P1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "PowerReal_P_Phase_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "Real P P3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "PowerReal_P_Phase_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "Real P P3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smartmeter",
     "select": [
      [
       { "params": [ "PowerReal_P_Phase_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Inverter Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Power AC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "PAC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Storage Temps ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storage",
     "select": [
      [
       { "params": [ "Temperature_Cell" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "Frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "FAC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "AC L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "UAC_L1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "AC L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "UAC_L2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "AC L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "UAC_L3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "DC 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "UDC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "DC 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "UDC_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "DC Battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storage",
     "select": [
      [
       { "params": [ "Voltage_DC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "AC L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "IAC_L1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "AC L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "IAC_L2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "AC L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "IAC_L3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "DC 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "IDC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "DC 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "IDC_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    },
    {
     "alias": "DC Battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storage",
     "select": [
      [
       { "params": [ "Current_DC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Current max capacity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storage",
     "select": [
      [
       { "params": [ "Capacity_Maximum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Max designed capacity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storage",
     "select": [
      [
       { "params": [ "DesignedCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}